SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS movimiento;
DROP TABLE IF EXISTS deuda;
DROP TABLE IF EXISTS Prestamo;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS estado;
DROP TABLE IF EXISTS tipo_estado;
DROP TABLE IF EXISTS log_service;

SET FOREIGN_KEY_CHECKS = 1;