 server.port=8081
spring.application.name=PrestaServicio

spring.datasource.hikari.schema=presta_bd_1
dbUrl=jdbc:mysql://localhost:3306/presta_bd_1?useSSL=true
dbUsername=presta_app
dbPassword=jean10
dbClassName=com.mysql.cj.jdbc.Driver